# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-StickyForm
version:      0.07
version_from: lib/HTML/StickyForm.pm
installdirs:  site
requires:
    Test::More:                    0
    Test::XML:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
